name: flutter_layout_grid
description: A grid-based layout system for Flutter, inspired by CSS Grid Layout
version: 0.10.2
homepage: https://github.com/madewithfelt/flutter_layout_grid

environment:
  flutter: '>=1.14.0 <2.0.0'
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  collection: ^1.15.0-nullsafety.5
  flutter:
    # When the ParentData changes were released
    # https://github.com/flutter/flutter/pull/48541
    sdk: flutter
  meta: ^1.3.0-nullsafety.6
  quiver: ^3.0.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
